# Generated by Django 4.2.1 on 2023-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
